#! /bin/bash

set -o errexit
set -o nounset
set -o pipefail

declare -r source_dir="$(dirname "$(readlink -f "${BASH_SOURCE}")")"

declare -A dotfiles=(
[.aliases]="${HOME}"
[.amzn_aliases]="${HOME}"
[.profile]="${HOME}"
[.vimrc]="${HOME}"
[.bashrc]="${HOME}"
[.gitconfig]="${HOME}"
[.git-prompt.sh]="${HOME}"
)

declare -A repositories=(
"ppa:mithrandie/csvq"
"ppa:rael-gc/rvm"
)

declare -r PACKAGES=(
"byobu"
"htop"
"gcc"
"vim"
"curl"
"xclip"
"openjdk-8-jdk"
"openjdk-11-jdk"
"openjdk-17-jdk"
"jq"
"csvq"
"libfuse2"
"make"
"libssl1.0.0"
"texlive-latex-base"
"texlive-latex-recommended"
"latexmk"
"texlive-latex-extra"
"remmina"
"remmina-plugin-vnc"
"rvm"
)

function install_dotfile() {
  local dotfile="$1"
  local install_path=$(dirname "$2/$dotfile")
  mkdir -p "${install_path}"
  local cmd=(ln -fs "${source_dir%%/}/files/${dotfile}" "${install_path%%/}/${dotfile}")
  echo "!installing ${dotfile}: ${cmd[@]}"
  "${cmd[@]}"
}

function add_apt_repository() {
  local repo="$1"
  local cmd=(sudo add-apt-repository ${repo})
  echo "installing ${repo}"
  "${cmd[@]}"
}

function main() {

  # apt repository attachment
  for repo in "${!repositories[@]}"; do
    add_apt_repository "${repo}"
  done

  # package installations
  for dotfile in "${!dotfiles[@]}"; do
    install_dotfile "${dotfile}" "${dotfiles[$dotfile]}"
  done

  # install nvm
  PROFILE=/dev/null bash -c $HOME/.dotfiles/node/install_nvm.sh

    # package manager & text editor setup
    sudo apt update -y &&  sudo apt upgrade -y
    sudo apt install -y "${PACKAGES[@]}"
    vim +BundleInstall +qall
    vim +GoInstallBinaries +qall
    bash
  }

  main "${@}"
